language: c
cache:
  directories:
    - arduino-sdk
env:
  global:
    - BOARD_NAME=uno
    - BOARD_DEVICE=/dev/null
    - ARDUINO_SDK_VERSION=1.8.5
addons:
  apt:
    packages:
      - cmake
      - gcc-avr
      - binutils-avr
      - avr-libc
      - avrdude
before_install:
  - if [[ ! -f arduino-sdk/arduino ]] ; then wget "https://downloads.arduino.cc/arduino-$ARDUINO_SDK_VERSION-linux32.tar.xz" -O arduino-sdk.tar.xz; mkdir -p arduino-sdk ; tar xf arduino-sdk.tar.xz -C arduino-sdk --strip-components 1 ; fi
  - export ARDUINO_SDK_PATH="$(pwd)/arduino-sdk"
script:
  - cd src
  - cmake -D ARDUINO_SDK_PATH="$ARDUINO_SDK_PATH" ..
  - make
